import React from 'react';
import { Sparkles, ArrowRight, Home } from 'lucide-react';

export default function SharePage({ id }) {
  const supabaseUrl = import.meta.env.PUBLIC_SUPABASE_URL || "https://kpxguxfylqszqsznqmqq.supabase.co";
  const imageUrl = `${supabaseUrl}/storage/v1/object/public/frames/${id}.png`;

  const handleGoHome = () => {
    window.location.href = '/';
  };

  const isFormatA = id.startsWith('frame');

  return (
    <div className="w-full max-w-4xl mx-auto px-4 py-12 flex flex-col items-center">
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-1.5 px-4 py-1.5 bg-brand-forest text-brand-yellow border border-brand-gold/20 rounded-full text-xs font-mono font-semibold mb-4 custom-shadow-sm">
          Verified Goa status
        </div>
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-brand-forest mb-2">
          Hacker House Goa 2026 Badge
        </h1>
        <p className="text-sm text-mute">
          This card was custom generated by a verified attendee.
        </p>
      </div>

      {/* Main card display */}
      <div className={`w-full bg-canvas border border-hairline custom-shadow-xl overflow-hidden rounded-lg p-4 md:p-6 mb-8 flex flex-col items-center justify-center max-w-2xl ${
        isFormatA ? 'aspect-square' : 'aspect-[16/9]'
      }`}>
        <img
          src={imageUrl}
          alt="Hacker House Goa 2026 Badge"
          className="w-full h-full object-contain rounded-md"
          onError={(e) => {
            e.target.src = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&fit=crop";
            alert("Could not load the shared image. Falling back to default preview.");
          }}
        />
      </div>

      {/* Action CTA */}
      <div className="flex flex-col sm:flex-row gap-4 w-full justify-center max-w-md">
        <button
          onClick={handleGoHome}
          className="flex-1 inline-flex items-center justify-center gap-2 bg-brand-pink text-white py-3.5 px-6 rounded-pill font-bold hover:bg-opacity-95 transition-all custom-shadow-sm cursor-pointer border border-brand-pink/20"
        >
          Claim Your Badge <ArrowRight className="w-4.5 h-4.5" />
        </button>
      </div>
    </div>
  );
}
